services:
  geocoding-service:
    image: geocoding-service
    build:
      context: .
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    expose:
      - "8091"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app_network